// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLESS.Data;

namespace QLESS.Data.Migrations
{
    [DbContext(typeof(QLESSContext))]
    [Migration("20201122164640_InitialCardRegTypeData")]
    partial class InitialCardRegTypeData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("QLESS.Domain.Model.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal>("CardLoad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CardRegTypeId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("LastName")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("LastUsed")
                        .HasColumnType("datetime2");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("QLESS.Domain.Model.CardLoadHist", b =>
                {
                    b.Property<Guid>("CardLoadRef")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CardLoadDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CardLoadFr")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CardLoadTo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Fare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FareDailyAdditionalDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FareDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CardLoadRef");

                    b.ToTable("CardLoadHists");
                });

            modelBuilder.Entity("QLESS.Domain.Model.CardRegType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CardRegTypeDesc")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CardRegTypeFormat")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<decimal>("DailyAdditionalDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaxDailyAdditionalDiscount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CardRegTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
